 export  const Category = {
    CATEGORY_1: 'CATEGORY_1',
    CATEGORY_2: 'CATEGORY_2',
    CATEGORY_3: 'CATEGORY_3',
    CATEGORY_4: 'CATEGORY_4',
    CATEGORY_5: 'CATEGORY_5',
    CATEGORY_6: 'CATEGORY_6',
    CATEGORY_7: 'CATEGORY_7',
  };

